Update lpu_dev

diff --git a/lpu_dev b/lpu_dev
--- a/lpu_dev
+++ b/lpu_dev
@@ -1,225 +1,240 @@
 #!/bin/bash
-### Function Definitions ###
+# Web Host Log Parsing Utility
+# @filename lpu.sh
+# @created 2022.08.23
+# @version 2022.12.21+15:15
+
+# Check that we are running as root, otherwise make it so
+[ $EUID -ne 0 ] && echo "[WARN] User not running as root" && sudo -s $0
+[ $EUID -eq 0 ] && echo "[INFO] User running as root"
+[ $EUID -ne 0 ] && exit 0
+
+# Configure global logging
+log_file="/var/log/lpu.log" # Path to log file
+#exec 3>&1 4>&2
+#trap 'exec 2>&4 1>&3' 0 1 2 3
+#exec 1>$log_file 2>&1
+
+# Everything below will be logged to "$log_file":
+
+relative_script_path="$0"
+absolute_script_path="$(readlink -f $0)"
+script_name="${absolute_script_path##*/}"
+echo -e "\n[INFO] Execution of ${script_name} started at $(date +"%Y-%m-%d_%H:%M:%S")"
+
+### Configuration Information ###
+base_directory="$(dirname "${absolute_script_path}")" #"/opt/lpu" # Base working directory
+config_file="${base_directory}/lpu.conf" #"/etc/lpu.conf" # Path to config file
+functions_file="${base_directory}/functions.sh"
+temp_directory="${base_directory}/tmp" # Temporary working directory
+package_directory="${base_directory}/deliverable" # Directory to save reports in
+# Default selections for parse term parameters
+term_period="month" # Length of term to parse, e.g. hour, day, month, year, or all
+term_target="last month" # String datetime describing a point within the desired term_period
+# Hashing preferences
+# Must be set before any hashing is done, clearly
+host_hash_start=1
+host_hash_stop=12
+site_hash_start=1
+site_hash_stop=24
+
+# Source config if it exists
+[ -f $config_file ] && source $config_file
+[ -f $functions_file ] && source $functions_file
+
+debug_initial_configuration=$(cat <<EOF
+Default Configuration:
+relative_script_path = $relative_script_path
+absolute_script_path = $absolute_script_path
+base_directory = $base_directory
+config_file = $config_file
+temp_directory = $temp_directory
+package_directory = $package_directory
+log_file = $log_file
+term_period = $term_period
+term_target = $term_target
+host_hash_start = $host_hash_start
+host_hash_stop = $host_hash_stop
+site_hash_start = $site_hash_start
+site_hash_stop = $site_hash_stop
+EOF
+)
+echo "[INFO] ${debug_initial_configuration}"
+
+### Initialization ###
+# Create the working directory if it doesn't exist; then change to it, regardless
+[ ! -d $base_directory ] && mkdir $base_directory;
+cd $base_directory || exit 1
+
+# Check that the current working directory is the prescribed base directory, otherwise error out
+[ "$(pwd)" != "${base_directory}" ] && echo "[ERR] Failed to change into base directory." && exit 1
+
+# Create the package directory for deliverables if it doesn't already exist
+[ ! -d $package_directory ] && mkdir $package_directory;
+
+# Remove any pre-existing temp directory; then create one, regardless
+[ -d $temp_directory ] && rm -rf $temp_directory;
+mkdir -p $temp_directory
+
+# Create subdirectories for 'sites', 'host', and 'manager' under the temp directory
+mkdir -p $temp_directory/{conf,logs,sites}
+
+# Pull target date information
+year=$(date -d "$term_target" +%Y) # term_target's year
+month=$(date -d "$term_target" +%b) # term_target's month, as formatted by Apache
+dom=$(date -d "$term_target" +%d) # term_target's day of the month
+iso_date=$(date -d "$term_target" +%F) # term_target's full date; like %+4Y-%m-%d
+short_date="${iso_date//-/}"
+timezone=$(date -d "$term_target" +%Z) # Alphabetic time zone abbreviation, e.g. EST
+# Generate a runtime timestamp
+timestamp=$(date +"%Y%m%d_%H%M%S") # Timestamp
+
+debug_time_info=$(cat <<EOF
+Datetime Information:
+	year = $year
+	month = $month
+	dom = $dom
+	iso_date = $iso_date
+	timezone = $timezone
+	timestamp = $timestamp
+EOF
+)
+echo "[INFO] ${debug_time_info}"
+
+# Check that the working directory is empty of any '*.gz' files, otherwise remove them
+ls *.gz > /dev/null 2>&1 && rm *.gz
+
+# Generate a hash of the current hostname
+#plain_host=$(hostname | xargs)
+#hashed_host=$(host_hash_function "$plain_host")
+#debug_host_hash=$(cat <<EOF
+#Host Information:
+#	hashed_host = $hashed_host
+#EOF
+#)
+#echo "[INFO] ${debug_host_hash}"
 
 
+##### Main Process #####
 
-### Wait for the user to press any key before continuing
-# Useful for debugging
-# Ex: await
-await() { echo -e "\n\n$1"; read -rsn1 -p "Press any key to continue" && echo -e "\n\n"; }
+## Pull access logs from each site's home directory into $base_directory
+case "$term_period" in
+	d|day|Day) cp /home/*/logs/*-${month}-${year}.gz ./ ;;
+	m|month|Month) cp /home/*/logs/*-${month}-${year}.gz ./ ;;
+	y|year|Year) cp /home/*/logs/*-${year}.gz ./ ;;
+	*) ;;
+esac
+# Iterate through the gzipped log files in $base_directory
+echo "[INFO] Entering for-loop at $(date +"%Y-%m-%d_%H:%M:%S")"
+for zipped_log in *.gz; do
 
-
-### Get the current timestamp formatted YYYY-MM-DD+hh:mm:ss # or however you want
-# Ex: get_timestamp
-get_timestamp() { date +"%Y-%m-%d+%H:%M:%S"; }
-
-
-### Hash and cut a supplied string 
-# Requres a string to hash, initial cut index, and a final cut index
-# Also accepts single-lined piped input for the string_to_hash argument
-# Prints result to stdout
-# Ex: hash_string --string-to-hash="Lorem ipsum dolor sit amet" --start-cut=12 --stop-cut=24 --hash-function=sha512sum
-# Ex: echo "foo" | hash_string
-hash_string() {
-	local string_to_hash
-	local start_cut 
-	local stop_cut
-	local hash_function
-	start_cut=1
-	stop_cut=12
-	hash_function="/usr/bin/sha512sum"
-	# Check to see if a pipe exists on stdin.
-	if [ -p /dev/stdin ]; then
-		# If we want to read the input line by line
-		while IFS= read line; do
-			string_to_hash="${line}"
-		done
-		# Or if we want to simply grab all the data, we can simply use cat instead
-		# cat
-	fi
-	for arg in "$@"; do
-        case "$arg" in
-            -s=*|--string-to-hash=*) string_to_hash="${arg#*=}" ;;
-            -c0=*|--start-cut=*) start_cut="${arg#*=}" ;;
-            -c1=*|--stop-cut=*) stop_cut="${arg#*=}" ;;
-            -a=*|--hash-function=*) hash_function="${arg#*=}" ;;
-			*) ;;
-        esac
-    done
-	case "$hash_function" in 
-		"sha256"|"sha256sum"|"/usr/bin/sha256sum") hash_function=sha256sum ;;
-		"sha512"|"sha512sum"|"/usr/bin/sha512sum") hash_function=sha512sum ;;
-		*) hash_function=sha512sum ;;
-	esac
-	echo "${string_to_hash}" | $hash_function | cut -c "${start_cut}-${stop_cut}";
-}
-
-### [LEGACY] Hash and cut functions for site and vps hostnames
-## INFO: These require the appropriate hash_start and hash_stop variables be defined
-## INFO: We'll have a general hash_string function shortly
-# Takes in the strings from standard input with no flags
-# Returns the hashed and cut resulting string
-# Ex: hash_site "google.com"
-hash_site() { echo "$1" | sha256sum | cut -c "${site_hash_start}-${site_hash_stop}"; }
-host_hash_function() { echo "$1" | sha256sum | cut -c "${host_hash_start}-${host_hash_stop}"; }
-
-## Find and replace stand-in
-# Takes in three inputs; the unmasked string, the masked string, and the file to obfuscate
-# Ex: mask_all_matches --unmasked-string="foo" --masked-string="bar" --file-to-mask="tmp.txt"
-# Ex: mask_all_matches -u="foo" -m="bar -f="tmp.txt"
-mask_all_matches() { 
-	local unmasked_string
-	local masked_string 
-	local file_to_mask
-	for arg in "$@"; do
-        case "$arg" in
-            -u=*|--unmasked-string=*) unmasked_string="${arg#*=}" ;;
-			-m=*|--masked-string=*) masked_string="${arg#*=}" ;;
-			-f=*|--file-to-mask=*) file_to_mask="${arg#*=}" ;;
-            *) ;;
-        esac
-    done
-	[ ! -f $file_to_mask ] && echo "File does not exist"
-	[ -f $file_to_mask ] && sed -i "s/${unmasked_string}/${masked_string}/gi" "$file_to_mask"
-}
-
-### WARNING: Modifies file in place
-## Appends a given string to all lines in a file
-# Requires two inputs, a string to append and file to append to
-# Ex: append_all_lines --suffix-string="test" --file-to-append="tmp.txt"
-# Ex: append_all_lines -s="test" -f="tmp.txt"
-append_all_lines() {
-	local suffix_string
-	local file_to_append
-	for arg in "$@"; do
-        case "$arg" in
-            -s=*|--suffix-string=*) suffix_string="${arg#*=}" ;;
-			-f=*|--file-to-append=*) file_to_append=$(echo "${arg#*=}" | xargs) ;;
-            *) ;;
-        esac
-    done
-	[ ! -f $file_to_append ] && echo "File does not exist"
-	[ -f $file_to_append ] && sed -i "s/$/ ${suffix_string}/" $file_to_append
-}
-
-## Remove last ".*" extensions from a string
-# Accepts string input through stdin $1
-# Ex: strip_last_extensions "test.tar.gz"
-strip_last_extension () { echo $1 | sed -e 's/\.[^.]*[^.]*$//'; }
-# Ex: strip_gz_extension "test.tar.gz" 
-strip_gz_extension () { echo $1 | sed -e 's/\.gz$//'; }
-##
-
-## Wrapped file transfer function
-# Requires a valid and properly configured .ssh/config file, 
-# with the transfer destination set up as a known host
-# https://linuxize.com/post/using-the-ssh-config-file/
-# https://unix.stackexchange.com/questions/94421/how-to-use-ssh-config-setting-for-each-server-by-rsync
-transfer_package () {
-	local source_path
-	local destination_host
-	local destination_path
-	for arg in "$@"; do
-        case "$arg" in
-            -s=*|--source-path=*) source_path="${arg#*=}" ;;
-			-h=*|--destination-host=*) destination_host="${arg#*=}" ;;
-			-d=*|--destination-path=*) destination_path="${arg#*=}" ;;
-            *) ;;
-        esac
-    done 
-	# Backup over SSH with non-standard port
-	# Assumes a .ssh/config entry already exists for now
-	rsync -av $source_path $destination_host:$destination_path
-}
-
-
-replace_all() { 
-	local initial_string
-	local final_string 
-	local target_path
-	local recursive_flag
-	for arg in "$@"; do
-        case "$arg" in
-            -u=*|--initial-string=*) initial_string="${arg#*=}" ;;
-			-m=*|--final-string=*) final_string="${arg#*=}" ;;
-			-f=*|--target-path=*) target_path="${arg#*=}" ;;
-			-r|--recursive) recursive_flag=1 ;;
-            *) ;;
-        esac
-    done
-	if grep -q $initial_string $target_path ; then 
-		if [ ! -f $target_path ]; then 
-			if [ ! -d $target_path ]; then
-				echo "File or path does not exist"
-			fi
-		fi
-		if [ -d $target_path ]; then 
-			#echo "Target path is a directory"
-			if [ $recursive_flag ]; then 
-				find $target_path -type f | xargs sed -i "s/${initial_string}/${final_string}/gi"
-			fi
-		else
-			if [ -f $target_path ]; then
-				#echo "Target path is a file"
-				sed -i "s/${initial_string}/${final_string}/gi" $target_path
-			fi
-		fi
-	fi
-}
-
-mask_all() { 
-	local unmasked_string
-	local target_path
-	local hash_function
-	local start_cut
-	local stop_cut 
-	if [ -p /dev/stdin ]; then
-		while IFS= read line; do
-			target_path="${line}"
-		done
-	fi
-	for arg in "$@"; do
-		case "$arg" in
-			-s=*|--unmasked-string=*) unmasked_string="${arg#*=}" ;;
-			-f=*|--target-path=*) target_path="${arg#*=}" ;;
-			-h=*|--hash-function=*) hash_function="${arg#*=}";;
-			-c0=*|--start-cut=*) start_cut="${arg#*=}" ;;
-			-c1=*|--stop-cut=*) stop_cut="${arg#*=}" ;;
+	if [ -f $zipped_log ]; then
+	  # Unzip the current file
+	  gunzip "$zipped_log"
+	  # Strip the '.gz' extension from zipped_log and save it for reference
+	  #unzipped_log=$(echo $zipped_log | sed -e s/\.gz$//)
+		unzipped_log=$(strip_gz_extension "$zipped_log")
+	  # Extract logs from the previous day into a separate file in $temp_directory
+		case "$term_period" in
+			d|day|Day) grep "${dom}/${month}/${year}" $unzipped_log >> "${temp_directory}/sites/${unzipped_log}" ;;
+			m|month|Month) grep ".*/${month}/${year}" $unzipped_log >> "${temp_directory}/sites/${unzipped_log}" ;;
+			y|year|Year) grep ".*/.*/${year}" $unzipped_log >> "${temp_directory}/sites/${unzipped_log}" ;;
 			*) ;;
 		esac
-	done
-	#masked_string=$(hash_string --string-to-hash="$unmasked_string" --hash-function="$hash_function" --start-cut=$start_cut --stop-cut=$stop_cut)
-	masked_string=$(echo "$unmasked_string" | hash_string)
-	[ -n $unmasked_string ] && replace_all --initial-string=$unmasked_string --final-string=$masked_string target-path=$target_path --recursive
-}
+		# Strip the TLD from the FQDN to get a bare domain name
+		#current_site=$(echo $unzipped_log | sed -e 's/\.[^.][^.]*$//')
+		current_site=$(strip_last_extension "$unzipped_log")
+		# Hash the current sitename
+		#hashed_site=$(site_hash_function "$current_site")
+		hashed_site=$(echo "$current_site" | hash_string)
+		### Only used for debugging ###
+		debug_site_info=$(cat <<	EOF
+	current_site = $current_site
+	hashed_site = $hashed_site
+	zipped_log = $zipped_log
+	unzipped_log = $unzipped_log
+EOF
+		)
+		#echo "[INFO] ${debug_site_info}"
+		echo "[INFO] Processing ${hashed_site} : $(echo ${unzipped_log} | sed "s/${current_site}/${hashed_site}/gi")"
+	###############################
+		# Append site and hostname to the end of each line in the logfile
+		append_all_lines --suffix-string="${hashed_site}" --file-to-append="${temp_directory}/sites/${unzipped_log}"
+		#sed -i "s/$/ ${hashed_site}/" "${temp_directory}/sites/${unzipped_log}"
+		#sed -i "s/$/ ${hashed_site} ${hashed_host}/" "${temp_directory}/sites/${unzipped_log}"  # <-- Maybe used later
+		# Mask instances of the hostname occurring in the logs <-- Does not mask any instances outside of own logs
+		#sed -i "s/${current_site}/${hashed_site}/gi" "${temp_directory}/sites/${unzipped_log}"
+		# Rename logfile with hashed domain name
+		mv $temp_directory/sites/$unzipped_log $temp_directory/sites/$hashed_site
+	    # Re-zip the current file (so it can be identified for deletion), then on to the next
+		gzip $unzipped_log
+	fi
+done
+echo "[INFO] Exiting for-loop at $(date +"%Y-%m-%d_%H:%M:%S")"
 
-#check_var_is_array() { echo "$(declare -p "$1" 2> /dev/null | grep -q '^declare \-a')" }
+echo -e "[INFO] Copying configuration files \n"
+[ -n $existing_conf_files ] && ( for cf in ${existing_conf_files[@]}; do
+	echo -e "    $cf"
+	[ -f $cf ] && rsync $cf $temp_directory/conf/
+done )
+echo -e "[INFO] Copying other log files \n"
+[ -n $existing_log_files ] && ( for lf in ${existing_log_files[@]}; do
+	echo -e "    $lf"
+	[ -f $lf ] && rsync $lf $temp_directory/logs/;
+done )
 
 
+# Mask host name
+echo "[INFO] Masking unhashed user info within files under the temp directory"
 
-# Mask cPanel User Info
-mask_cpuser_info() {
-	user_info=( "USER=" "IP=" "DNS" "CONTACTEMAIL" )
-	for user_file in /var/cpanel/users/*; do 
-		declare -a strings_to_mask 
+for user_file in /var/cpanel/users/* ; do
+	echo "[INFO] Collecting strings to mask"
+	declare -a strings_to_mask
+	if [ -f $user_file ] ; then
+		#unmasked_string=""
+		#masked_string=""
 		for info in ${user_info[@]}; do
+			echo -e "    $info"
 			strings_to_mask+=($(grep "$info" $user_file | cut -f2 -d '=' | xargs))
-		done 
-		for unmasked_string in ${strings_to_mask[@]}; do
-			mask_all --unmasked-string="$unmasked_string" --target-path=$1 --recursive
+			#unmasked_string=$(grep "$info" $user_file | cut -f2 -d '=' | xargs)
+			#unset masked_string
+			#unset unmasked_string #strings_to_mask
 		done
-		unset strings_to_mask
-	done
-}
+	fi
+done
+echo "[INFO] Masking strings"
+for unmasked_string in ${strings_to_mask[@]}; do
+	if [ ! -z $unmasked_string ] ; then
+		masked_string=$(echo $unmasked_string | hash_string)
+		echo -e "    $masked_string"
+		#replace_all --initial-string="$unmasked_string" --final-string="$masked_string" --target-path=$temp_directory --recursive
+		echo "        sites"
+		mask_all --unmasked-string="$unmasked_string" --target-path=$temp_directory/sites/* #--recursive
+		echo "        logs"
+		mask_all --unmasked-string="$unmasked_string" --target-path=$temp_directory/logs/*
+		echo "        conf"
+		mask_all --unmasked-string="$unmasked_string" --target-path=$temp_directory/conf/*
+	fi
+done
+unset strings_to_mask
 
-randpw(){ < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16};echo;}
+# Append hashed host to the end of each log entry in the tmp/host subdirectory
+#find $temp_directory/host -type f | xargs sed -i "s/$/ ${hashed_host}/"
 
-change_cpuser_passwd() {
-	for user_file in /var/cpanel/users/*; do 
-		username=$(grep "USER=" $user_file | cut -f2 -d '=' | xargs)
-		passwd -S $username
-		password = randpw
-		echo "${username} | ${password}"
-		echo $password | passwd --stdin $username
-	done
-}
+# Remove trash before archiving
+echo "[INFO] Emptying trash"
+rm -rf "${temp_directory}/trash"
+
+### Create deliverable archive
+echo "[INFO] Creating archive and compressing"
+cp $log_file $temp_directory
+( cd $temp_directory && tar -czf "${package_directory}/${hashed_host}_${timestamp}_${term_period}_of_${short_date}.tar.gz" * )
+
+# Clean up working directory before we finish up
+echo "[INFO] Tidying up working directory"
+rm -rf $temp_directory
+rm *.gz
+
+# Exit gracefully
+echo "[INFO] Execution of ${script_name} complete at $(date +"%Y-%m-%d_%H:%M:%S")"
+echo -e "\n"
